apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: zuryka.com-tls
spec:
  secretName: zuryka.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: zuryka.com
  dnsNames:
    - zuryka.com
    - www.zuryka.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - zuryka.com
          - www.zuryka.com
